import "./globals.css";
import { LivepeerProvider } from "./livepeer-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LivepeerProvider>{children}</LivepeerProvider>
      </body>
    </html>
  );
}
